# Copyright 2024 Innkeeper GoTribe <https://www.gotribe.cn>. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file. The original repo for
# this file is https://www.gotribe.cn



apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app # 资源标签
  name: app # 资源名称
spec:
  replicas: 2 # 副本数
  progressDeadlineSeconds: 10
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - app
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - command:
        - /opt/app/bin/app
        - --config=/etc/app/app.yaml
        image: "dengmengmian/app-amd64:v1.0.0"
        name: app
        ports:
        - containerPort: 8443
          name: secure
          protocol: TCP
        - containerPort: 8080
          name: insecure
          protocol: TCP
        - containerPort: 9090
          name: rpc
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          failureThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          failureThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        startupProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          failureThreshold: 10
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 512Mi
        imagePullPolicy: Always
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/app/app.yaml
          name: app
          subPath: app.yaml
        - mountPath: /etc/app/cert
          name: app-cert
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
            {}
      terminationGracePeriodSeconds: 5
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: app.yaml
            path: app.yaml
          name: app
        name: app
      - configMap:
          defaultMode: 420
          name: app-cert
        name: app-cert
