// Copyright 2024 Innkeeper GoTribe <https://www.gotribe.cn>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file. The original repo for
// this file is https://www.gotribe.cn

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: app/v1/app.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GoTribeClient is the client API for GoTribe service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoTribeClient interface {
	ListUser(ctx context.Context, in *ListUserRequest, opts ...grpc.CallOption) (*ListUserResponse, error)
}

type gotribeClient struct {
	cc grpc.ClientConnInterface
}

func NewGoTribeClient(cc grpc.ClientConnInterface) GoTribeClient {
	return &gotribeClient{cc}
}

func (c *gotribeClient) ListUser(ctx context.Context, in *ListUserRequest, opts ...grpc.CallOption) (*ListUserResponse, error) {
	out := new(ListUserResponse)
	err := c.cc.Invoke(ctx, "/v1.GoTribe/ListUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoTribeServer is the server API for GoTribe service.
// All implementations must embed UnimplementedGoTribeServer
// for forward compatibility
type GoTribeServer interface {
	ListUser(context.Context, *ListUserRequest) (*ListUserResponse, error)
	mustEmbedUnimplementedGoTribeServer()
}

// UnimplementedGoTribeServer must be embedded to have forward compatible implementations.
type UnimplementedGoTribeServer struct {
}

func (UnimplementedGoTribeServer) ListUser(context.Context, *ListUserRequest) (*ListUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUser not implemented")
}
func (UnimplementedGoTribeServer) mustEmbedUnimplementedGoTribeServer() {}

// UnsafeGoTribeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoTribeServer will
// result in compilation errors.
type UnsafeGoTribeServer interface {
	mustEmbedUnimplementedGoTribeServer()
}

func RegisterGoTribeServer(s grpc.ServiceRegistrar, srv GoTribeServer) {
	s.RegisterService(&GoTribe_ServiceDesc, srv)
}

func _GoTribe_ListUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoTribeServer).ListUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.GoTribe/ListUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoTribeServer).ListUser(ctx, req.(*ListUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GoTribe_ServiceDesc is the grpc.ServiceDesc for GoTribe service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoTribe_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.GoTribe",
	HandlerType: (*GoTribeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListUser",
			Handler:    _GoTribe_ListUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/v1/app.proto",
}
